Integrate a D3.js charting library
nsoss/srce-desktop-app pull request #30
Opened 2019-11-20 16:15 UTC by markoT97

2019-11-25 10:44 UTC, coka requested changes
This doesn't compile.

```
./src/charts/BarChart.js
Module not found: Can't resolve 'd3-array' in '/Users/coka/work/srce-desktop-app/src/charts'
```

You need to commit the updates to `package.json` which include `d3-array`, `d3-scale`, etc.

2019-11-25 10:53 UTC, markoT97 commented
> This doesn't compile.
> 
> ```
> ./src/charts/BarChart.js
> Module not found: Can't resolve 'd3-array' in '/Users/coka/work/srce-desktop-app/src/charts'
> ```
> 
> You need to commit the updates to `package.json` which include `d3-array`, `d3-scale`, etc.

I will fix it in a minute, I'm kind of pushed wrong package.json...

2019-11-25 11:22 UTC, coka commented
@markoT97 Now the commit message is "Implement calendar component".

2019-11-28 09:52 UTC, coka approved these changes

2019-11-28 09:52 UTC, merged