Il/validate entries
nsoss/srce-desktop-app pull request #77
Opened 2019-12-20 15:08 UTC by ivanalaz

2019-12-23 14:44 UTC, coka requested changes

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> -    };
This is still a valid way to declare component state. Different syntax, same result. When in doubt, try to adapt to the existing code.

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> +        this.handleBlur = this.handleBlur.bind(this);
You don't need to bind methods if they're declared as arrow functions. See [here](https://medium.com/@nikolalsvk/loosing-bind-this-in-react-8637ebf372cf).

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> +        const regex = /^([A-Za-z]+\s)*[A-Za-z]*$/;
This won't match for "Š", "Č", "Ć", etc.

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> +        let err = '';
Use full words here, for readability. Also, you an use the shorthand:
```javascript
let {name, value} = event.target
```

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> +              });
Is there are way to remove this repetition?

2019-12-23 14:44 UTC, coka commented on src/administration/components/AdminPanel.jsx
> +    validateField(fieldName, value) {
If your field is a component, you can validate at that level, instead of procedurally validating each field in the parent.

2019-12-23 14:44 UTC, coka commented on src/calls/components/CallsView.jsx
> +      //  this.state ={name: "calls"}
Remove commented code.

2019-12-23 14:44 UTC, coka commented on src/navigation/components/Navigation.jsx
> +export default Navigation;
Please configure your editor to insert newlines. Reference [this](https://github.com/nsoss/srce-desktop-app/pull/27#discussion_r348381193) comment from a previous review for the rationale.

2020-01-14 10:37 UTC, coka requested changes
I would like to merge this, but let's resolve the conflicts first.

2020-01-14 10:37 UTC, coka commented on src/Helpers.css
> +    /*margin-bottom: 0;*/
Please remove commented code.

2020-01-14 10:37 UTC, coka commented on src/navigation/components/Navigation.jsx
> +export default Navigation;
This is still unresolved.

2020-01-14 10:56 UTC, ivanalaz commented on src/administration/components/AdminPanel.jsx
> +                    <ValidationForm addVolunteerFunc={this.handleAddVolunteer}/>
I'll resolve conflicts, but this function call is still not working properly. You get redirected to the 'home page' after you add a volunteer... @coka

2020-01-15 13:03 UTC, coka approved these changes

2020-01-15 13:03 UTC, merged